# Generated by Django 6.0.6 on 2026-07-04 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonbrand',
            name='flat_name',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='canonmodel',
            name='flat_name',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='keyboard_tracker.canonmodel'),
        ),
    ]
