# Generated by Django 6.0.6 on 2026-07-06 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_tracker', '0004_canonmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='keyboard_tracker.canonmodel'),
        ),
    ]
