# Generated by Django 6.0.6 on 2026-06-30 11:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanonBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_item_id', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('image_urls', models.JSONField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('marketplace', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('SOLD', 'Sold')], db_index=True, default='ACTIVE', max_length=20)),
                ('affiliate_url', models.TextField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('miss_count', models.IntegerField(blank=True, default=0)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'listings',
            },
        ),
        migrations.CreateModel(
            name='TempSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_item_id', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('buying_options', models.JSONField(blank=True, null=True)),
                ('image_urls', models.JSONField(blank=True, null=True)),
                ('item_url', models.TextField(blank=True, null=True)),
                ('affiliate_url', models.TextField(blank=True, null=True)),
                ('seller_username', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_feedback_score', models.IntegerField(blank=True, null=True)),
                ('seller_feedback_percent', models.FloatField(blank=True, null=True)),
                ('categories', models.JSONField(blank=True, null=True)),
                ('marketplace', models.CharField(blank=True, max_length=100, null=True)),
                ('item_country', models.CharField(blank=True, max_length=2, null=True)),
                ('item_city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('item_created_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temp_summaries',
            },
        ),
        migrations.CreateModel(
            name='CanonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='keyboard_tracker.canonbrand')),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='ModelAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='keyboard_tracker.canonmodel')),
            ],
            options={
                'db_table': 'model_aliases',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='keyboard_tracker.listing')),
            ],
            options={
                'db_table': 'price_history',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='keyboard_tracker.canonmodel')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='keyboard_tracker.product'),
        ),
        migrations.AddConstraint(
            model_name='canonmodel',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='uq_brand_model'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['listing', 'recorded_at', 'id'], name='ix_pricehistory_listing_time'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'marketplace'], name='ix_listings_marketplace_setnum'),
        ),
    ]
