# Generated by Django 6.0.6 on 2026-07-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_tracker', '0002_canonbrand_flat_name_canonmodel_flat_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='product',
        ),
        migrations.DeleteModel(
            name='ModelAlias',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
