# Generated by Django 6.0.6 on 2026-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_tracker', '0003_remove_product_model_remove_listing_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonmodel',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
