# Generated by Django 6.0.6 on 2026-07-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_tracker', '0005_listing_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='canonmodel',
            name='uq_brand_model',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='model',
        ),
        migrations.DeleteModel(
            name='CanonModel',
        ),
    ]
