# Generated by Django 6.0.6 on 2026-07-08 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_tracker', '0006_remove_canonmodel_uq_brand_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_size', models.CharField(blank=True, max_length=50, null=True)),
                ('switch_type', models.CharField(blank=True, max_length=100, null=True)),
                ('low_profile', models.BooleanField(default=False)),
                ('hall_effect', models.BooleanField(default=False)),
                ('optical', models.BooleanField(default=False)),
                ('hot_swap', models.BooleanField(default=False)),
                ('gasket_mount', models.BooleanField(default=False)),
                ('knob', models.BooleanField(default=False)),
                ('wireless', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('qmk', models.BooleanField(default=False)),
                ('via', models.BooleanField(default=False)),
                ('iso', models.BooleanField(default=False)),
                ('ansi', models.BooleanField(default=False)),
                ('barebones', models.BooleanField(default=False)),
                ('rgb', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specs', to='keyboard_tracker.canonbrand')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='keyboard_tracker.listing')),
            ],
        ),
    ]
