# Generated by Django 6.0.6 on 2026-07-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_tracker', '0007_specs'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='specs',
            table='specs',
        ),
    ]
