# Generated by Django 6.0.6 on 2026-07-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_tracker', '0008_alter_specs_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonbrand',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
