# Generated by Django 6.0.6 on 2026-07-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_tracker', '0009_canonbrand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonbrand',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
