# Generated by Django 6.0.6 on 2026-08-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_tracker', '0010_alter_canonbrand_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('feature', 'Feature'), ('size', 'Size'), ('switch', 'Switch')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'category'), name='unique_specification_slug_category')],
            },
        ),
        migrations.CreateModel(
            name='SpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='keyboard_tracker.specification')),
                ('specs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='keyboard_tracker.specs')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('specs', 'specification'), name='unique_specs_specification')],
            },
        ),
    ]
