# Generated by Django 6.0.6 on 2026-08-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_tracker', '0011_specification_specvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canonbrand',
            name='flat_name',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='ansi',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='barebones',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='bluetooth',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='gasket_mount',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='hall_effect',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='hot_swap',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='knob',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='layout_size',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='low_profile',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='optical',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='qmk',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='rgb',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='switch_type',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='via',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='wireless',
        ),
    ]
